# Generated by Django 4.2.2 on 2023-06-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=10, unique=True)),
                ('email', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('Highest_Qualification', models.CharField(max_length=10)),
                ('Passedout_Year', models.IntegerField()),
                ('Resume', models.FileField(max_length=10, upload_to='')),
            ],
        ),
    ]
