# Generated by Django 4.2.2 on 2023-06-19 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('JobHUB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='groups',
            field=models.ManyToManyField(related_name='job_registrations', to='auth.group'),
        ),
        migrations.AddField(
            model_name='registration',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_registration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration',
            name='user_permissions',
            field=models.ManyToManyField(related_name='job_registrations', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Passedout_Year',
            field=models.CharField(max_length=20),
        ),
    ]
