# Generated by Django 4.2.2 on 2023-06-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobHUB', '0002_registration_groups_registration_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='registration',
            name='Passedout_Year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.CharField(max_length=10),
        ),
    ]
