# Generated by Django 4.2.2 on 2023-06-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobHUB', '0003_remove_registration_groups_remove_registration_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='Highest_Qualification',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='Passedout_Year',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='Resume',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='mobile',
        ),
    ]
