# Generated by Django 4.2.2 on 2023-06-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobHUB', '0004_remove_registration_highest_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='mobile',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
