# Generated by Django 4.2.2 on 2023-06-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobHUB', '0005_registration_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='pdf_file',
            field=models.FileField(default='default.pdf', upload_to='documents/{Resume}/'),
            preserve_default=False,
        ),
    ]
