# Generated by Django 4.2.2 on 2023-06-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobHUB', '0006_registration_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='Highest_Qualification',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('MCA', 'MCA'),('BSC', 'BSC')], default='B.Tech', max_length=6),
            preserve_default=False,
        )
    ]
        # migrations.AlterField(
        #     model_name='registration',
        #     name='pdf_file',
        #     field=models.FileField(default='default.pdf', upload_to='documents/{Resume}/'),
        # ),
    
