# Generated by Django 4.2.1 on 2023-06-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobHUB', '0007_registration_highest_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Highest_Qualification',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('MCA', 'MCA'), ('BCA', 'BCA'), ('BSC', 'BSC')], max_length=6),
        ),
        migrations.AlterField(
            model_name='registration',
            name='pdf_file',
            field=models.FileField(default='default.pdf', upload_to='documents/{Resume}/'),
        ),
    ]
