# Generated by Django 4.2.1 on 2023-06-20 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobHUB', '0008_alter_registration_highest_qualification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='Highest_Qualification',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='pdf_file',
        ),
    ]
