# Generated by Django 4.2.1 on 2023-06-20 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobHUB', '0012_registration_highest_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='Highest_Qualification',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='mobile',
        ),
    ]
