# Generated by Django 4.2.1 on 2023-06-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobHUB', '0018_registration_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='Highest_Qualification',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('MCa', 'MCA'), ('BCA', 'BCA'), ('BSC', 'BSC')], default='B.Tech', max_length=10),
        ),
    ]
