# Generated by Django 4.2.1 on 2023-06-22 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobHUB', '0021_javadeveloper_jobs_pythondeveloper_reactdeveloper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Company Name')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('javadeveloper', models.TextField(verbose_name='Java Developer Opportunities')),
                ('pythondeveloper', models.TextField(verbose_name='Python Developer Opportunities')),
                ('reactdeveloper', models.TextField(verbose_name='React Developer Opportunities')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobHUB.company', verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
            ],
        ),
        migrations.DeleteModel(
            name='javadeveloper',
        ),
        migrations.DeleteModel(
            name='jobs',
        ),
        migrations.DeleteModel(
            name='pythondeveloper',
        ),
        migrations.DeleteModel(
            name='reactdeveloper',
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobHUB.joblocation', verbose_name='Job Location'),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobHUB.joblocation', verbose_name='Location'),
        ),
    ]
