# Generated by Django 4.2.1 on 2023-06-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobHUB', '0022_company_job_joblocation_delete_javadeveloper_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='JobLocation',
        ),
    ]
