# Generated by Django 4.2.1 on 2023-06-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobHUB', '0025_delete_job_remove_registration_highest_qualification_and_more'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Job',
        # ),
        migrations.AddField(
            model_name='registration',
            name='Highest_Qualification',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('MCa', 'MCA'), ('BCA', 'BCA'), ('BSC', 'BSC')], default='B.Tech', max_length=10),
        ),
    ]
