# Generated by Django 4.2.1 on 2023-06-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobHUB', '0026_delete_job_registration_highest_qualification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.AddField(
            model_name='registration',
            name='pdf_file',
            field=models.FileField(default='default.pdf', upload_to='documents/{Resume}/'),
        ),
    ]
