# Generated by Django 4.2.1 on 2023-06-22 11:59

import JobHUB.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobHUB', '0027_delete_job_registration_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('mobile', models.CharField(default=JobHUB.models.calculate_default_mobile, max_length=10)),
                ('company_name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
    ]
