# Generated by Django 4.2.1 on 2023-06-22 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobHUB', '0031_myuser'),
    ]

    operations = [
       migrations.CreateModel(
            name='company',
            fields=[
                ('user', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='JobHUB.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='jobseeker',
            fields=[
                ('user', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='JobHUB.myuser')),
            ],
        ),
    ]
