# Generated by Django 4.2.1 on 2023-06-23 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobHUB', '0033_remove_jobseeker_user_remove_myuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobcreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(choices=[('React Developer', 'React developer'), ('Java Developer', 'Java developer'), ('Python Developer', 'Python developer'), ('Angular Developer', 'Angular developer')], default='React Developer', max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('experience', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        # migrations.RemoveField(
        #     model_name='jobseeker',
        #     name='user',
        # ),
        # migrations.RemoveField(
        #     model_name='myuser',
        #     name='groups',
        # ),
        # migrations.RemoveField(
        #     model_name='myuser',
        #     name='user_permissions',
        # ),
        # migrations.DeleteModel(
        #     name='company',
        # ),
        # migrations.DeleteModel(
        #     name='jobseeker',
        # ),
        # migrations.DeleteModel(
        #     name='MyUser',
        # ),
    ]
