# Generated by Django 4.2.1 on 2023-06-24 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobHUB', '0043_remove_jobseeker_user_remove_myuser_groups_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='company',
        #     name='user',
        # ),
        migrations.DeleteModel(
            name='jobcreate',
        ),
        # migrations.RemoveField(
        #     model_name='jobseeker',
        #     name='user',
        # ),
        # migrations.RemoveField(
        #     model_name='myuser',
        #     name='groups',
        # ),
        # migrations.RemoveField(
        #     model_name='myuser',
        #     name='user_permissions',
        # ),
        # migrations.DeleteModel(
        #     name='company',
        # ),
        # migrations.DeleteModel(
        #     name='jobseeker',
        # ),
        # migrations.DeleteModel(
        #     name='MyUser',
        # ),
    ]
