# Generated by Django 4.2.1 on 2023-06-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobHUB', '0044_remove_company_user_delete_jobcreate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobcreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(blank=True, choices=[('React Developer', 'React developer'), ('Java Developer', 'Java developer'), ('Python Developer', 'Python developer'), ('Angular Developer', 'Angular developer')], default='React developer', max_length=30, null=True)),
            ],
        ),
        # migrations.RemoveField(
        #     model_name='jobseeker',
        #     name='user',
        # ),
        # migrations.RemoveField(
        #     model_name='myuser',
        #     name='groups',
        # ),
        # migrations.RemoveField(
        #     model_name='myuser',
        #     name='user_permissions',
        # ),
        # migrations.DeleteModel(
        #     name='company',
        # ),
        # migrations.DeleteModel(
        #     name='jobseeker',
        # ),
        # migrations.DeleteModel(
        #     name='MyUser',
        # ),
    ]
