# Generated by Django 4.2.1 on 2023-06-24 06:04

import JobHUB.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobHUB', '0045_jobcreate_remove_jobseeker_user_remove_myuser_groups_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='jobseeker',
        #     name='user',
        # ),
        # migrations.RemoveField(
        #     model_name='myuser',
        #     name='groups',
        # ),
        # migrations.RemoveField(
        #     model_name='myuser',
        #     name='user_permissions',
        # ),
        migrations.AddField(
            model_name='jobcreate',
            name='company',
            field=models.CharField(blank=True, default='abc info tech', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobcreate',
            name='experience',
            field=models.CharField(default='0-1yr exp', max_length=30),
        ),
        migrations.AddField(
            model_name='jobcreate',
            name='location',
            field=models.CharField(default='Hyderabad', max_length=20),
        ),
        migrations.AddField(
            model_name='jobcreate',
            name='mobile',
            field=models.CharField(default=JobHUB.models.calculate_default_mobile, max_length=10),
        ),
        migrations.AddField(
            model_name='jobcreate',
            name='username',
            field=models.CharField(default=None, max_length=20),
        ),
        # migrations.DeleteModel(
        #     name='company',
        # ),
        # migrations.DeleteModel(
        #     name='jobseeker',
        # ),
        # migrations.DeleteModel(
        #     name='MyUser',
        # ),
    ]
