# Generated by Django 4.2.1 on 2023-06-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobHUB', '0050_remove_company_user_delete_jobseeker_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='company',
        #     name='user',
        # ),
        # migrations.DeleteModel(
        #     name='jobseeker',
        # ),
        migrations.AddField(
            model_name='jobcreate',
            name='job_role',
            field=models.CharField(blank=True, choices=[('React Developer', 'React developer'), ('Java Developer', 'Java developer'), ('Python Developer', 'Python developer'), ('Angular Developer', 'Angular developer')], default='React developer', max_length=30, null=True),
        ),
        # migrations.DeleteModel(
        #     name='company',
        # ),
        # migrations.DeleteModel(
        #     name='MyUser',
        # ),
    ]
