# Generated by Django 4.2.1 on 2023-06-24 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobHUB', '0051_remove_company_user_delete_jobseeker_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='company',
        #     name='user',
        # ),
        # migrations.DeleteModel(
        #     name='jobseeker',
        # ),
        # migrations.DeleteModel(
        #     name='company',
        # ),
        # migrations.DeleteModel(
        #     name='MyUser',
        # ),
    ]
