# Generated by Django 4.2.1 on 2023-06-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobHUB', '0055_remove_company_user_delete_jobseeker_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='company',
        #     name='user',
        # ),
        # migrations.DeleteModel(
        #     name='jobseeker',
        # ),
        migrations.AddField(
            model_name='registration',
            name='Highest_Qualification',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('MCa', 'MCA'), ('BCA', 'BCA'), ('BSC', 'BSC')], default='B.Tech', max_length=10),
        ),
        # migrations.DeleteModel(
        #     name='company',
        # ),
        # migrations.DeleteModel(
        #     name='MyUser',
        # ),
    ]
