# Generated by Django 4.2.1 on 2023-06-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobHUB', '0057_remove_company_user_delete_jobseeker_delete_company_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='company',
        #     name='user',
        # ),
        # migrations.DeleteModel(
        #     name='jobseeker',
        # ),
        migrations.AddField(
            model_name='registration',
            name='pdf_file',
            field=models.FileField(default='default.pdf', upload_to='documents/{Resume}/'),
        ),
        # migrations.DeleteModel(
        #     name='company',
        # ),
        # migrations.DeleteModel(
        #     name='MyUser',
        # ),
    ]
